### PR TITLE
Fix #409  added missing parameter to toggle initial time mode

### LINKED ISSUE #409: Bug: Creating a scheduled Session on a PC or Desktop should not show the Mobile time/date picker
Currently, when creating a scheduled session and setting the time the mobile version of the selector is shown. This is much harder to work with on a keyboard and mouse equipped PC than on a touch-friendly mobile devices.

On keyboard + mouse devices, we should default to using the desktop style input methods for setting time or date. The Mobile style should only be shown on touch devices. 

See the issue attached below:

Image

### PR DESCRIPTION
**Pull request by schalky**

### CODE REVIEW

**Review by ansells — COMMENTED** [review]
Is there the same thing for the date selector or are we fine with that as is for both mobile and web?

**Comment by blopker** [comment]
I put a PR out for upstream: https://github.com/GaspardMerten/date_field/pull/36. Hopefully they accept!

**Review by blopker — APPROVED** [review]
Looks good!

**Comment by blopker** [comment]
@ansells, do you have a screenshot of what you're talking about?

**Comment by ansells** [comment]
> @ansells, do you have a screenshot of what you're talking about?

I'm good with it:

image
image

**Review by ansells — APPROVED** [review]

**Comment by blopker** [comment]
Yeah, I think the default date picker is nice for web. Thanks for looking out though.

**Pull request merged**
