### PR TITLE
Feature/circe image

### LINKED ISSUE #283: Add images to Circle creation and edit flows
As a keeper, I need a way to add images to my circle sessions, so that people can easily identify and find my sessions.

**What Image Sizes**
We need to support at least two different sizes:
- a 1000x300 pixel (width x height) banner-style image
- a 300x300 pixel "circle highlight" image
- Web and mobile standard image formats should be supported: PNG, JPG, WEBP, HEIC, BMP
- any bit depth up to 32-bit should be supported
- transparency or matte channels should be supported
- should support two different image files for the two sizes

**What Image Size Shows Up Where**
- the 1000x300 appears only on the Circle or session profile page
- the 300x300 appears on the home screen (for the sessions being shown), or anywhere else in the UI where a summary or short list of circle sessions appear

**What to do if there are no Images provided**
- the system should programmatically generate placeholder images for the Keeper if they choose not to provide one
- these generated images could be something as simple as a random color and text overlay from the session title

**Where this setting appears**
- Whenever a circle or session is created
- Wherever a circle or session can be edited

**Who can change this setting**
- The Keeper who creates the circle or session
- Admins

### PR DESCRIPTION
**Pull request by schalky**
Fixes #283 
Support for images from a list of pre-canned 'themes' when creating a circle

### CODE REVIEW

**Review by ansells — APPROVED** [review]

**Comment by blopker** [comment]
Nice. Two issues I've seen. When testing as a non-keeper, selecting a theme seems to make no difference in the created circle. Where the image is supposed to be (in the circle) shows instead a circle with a letter in it. The other issue is the color of the circle seems non-deterministic, in that every time I leave the waiting room and go back to the home page, the color changes. I wonder if the color can be picked as a hash of the circle name? That would make it static.

**Comment by blopker** [comment]
Also, I'm not seeing where the image banner is showing, but I assume that's to come?

**Comment by micahp2** [comment]
Yes, the color should be fixed when the session is created so that everyone who sees it see the same thing.

And yes, there is a different view yet to be built where the banner image would go.

**Comment by schalky** [comment]
the private item seems to work fine when I redeployed the cloud function update that seems to likely have been overwritten on the server by another PR update. Changed the color to be an index based off hash of name. Tested and color stays consistent.

**Comment by blopker** [comment]
Ah, yes, this is the problem with only having one backend for all dev.

**Comment by blopker** [comment]
Also, nice trick with hashCode!

**Pull request merged**
